name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  # execute a cada 12 horas
  push:
    branches:
      - master  # ou 'main', dependendo da sua branch principal
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write  # Permissão para fazer push na branch output
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Create dist directory
        run: mkdir -p dist  # Cria a pasta dist se não existir

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg  # Garante que o arquivo vá para a pasta dist/

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist  # Certifique-se de que a pasta dist exista
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
